--- 
- name: (NRPE) install nagios packages
  apt:
    state: latest
    autoremove: true
    name:
      - monitoring-plugins-basic
      - monitoring-plugins-common
      - nagios-nrpe-server

- name: (NRPE) configure nrpe access
  ansible.builtin.lineinfile:
    path: /etc/nagios/nrpe_local.cfg
    regexp: 'allowed_hosts'
    line: "allowed_hosts=155.98.58.45"
  when: not ansible_check_mode
  notify: restart nagios-nrpe-server

# commenting out until we get a solution to host-specific limits
#- name: (NRPE) configure nrpe disk monitoring 
#  ansible.builtin.lineinfile:
#    path: /etc/nagios/nrpe_local.cfg
#    regexp: 'check_disk'
#    line: "command[check_disk_root]=/usr/lib/nagios/plugins/check_disk -w 10% -c 5% -p /"
#  when: not ansible_check_mode
#  notify: restart nagios-nrpe-server
#
#- name: (NRPE) configure nrpe load monitoring   
#  ansible.builtin.lineinfile:
#    path: /etc/nagios/nrpe_local.cfg
#    regexp: 'check_load'
#    line: "command[check_load]=/usr/lib/nagios/plugins/check_load -w 6,4,3 -c 10,8,6"
#  when: not ansible_check_mode
#  notify: restart nagios-nrpe-server

