#
# Handlers for compute role
#
---
- name: restart sshd
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted
    enabled: true

- name: systemctl daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
    