---
#
# This playbook will make sure the packges provided through apt are up
# to date (but will not reboot boxes; that is a different playbook)
#
- name: Install ubuntu-pro-client package
  ansible.builtin.apt:
    name:  ubuntu-pro-client
    state: latest
  when: ansible_facts['distribution'] == "Ubuntu"
- name: Set pro token
  set_fact:
    ubuntu_pro_token: "{{ 'C1HtrCfyJnQBaKfsRs59nBtnzeiUs' if ansible_virtualization_type == 'VMware' else 'C12BuMVKLDhwi6u8bSPQGTFxBmXs5f' }}"
  when: ansible_facts['distribution'] == "Ubuntu"
- name: Register with Ubuntu Pro
  ansible.builtin.command: "pro attach {{ ubuntu_pro_token }}"
  when: ansible_facts['distribution'] == "Ubuntu"
  register: reg_pro_attach
  changed_when: reg_pro_attach.rc == 0
  failed_when: (reg_pro_attach.rc != 0) and ('This machine is already attached to' not in reg_pro_attach.stderr_lines[0])

