---
- name: create install directory
  ansible.builtin.file:
    path: /tmp/tanium-install
    state: directory
    mode: '0755'

- name: copy Tanium source
  ansible.builtin.copy:
     src: Tanium-7.6.2.1247_Ubuntu-24.04_install.tar
     dest: /tmp/tanium-install

- name: extract Tanium source
  ansible.builtin.shell:
    chdir: /tmp/tanium-install
    cmd: tar xf ./Tanium-7.6.2.1247_Ubuntu-24.04_install.tar

- name: install Tanium
  ansible.builtin.shell:
    chdir: /tmp/tanium-install
    cmd: HOME=/tmp/tanium-install ./linux_install.sh -p taniumclient_7.6.2.1247-ubuntu24_amd64.deb -i tanium-init.dat -c CustomTags.txt

- name: delete Tanium source
  ansible.builtin.file:
    path: /tmp/tanium-install
    state: absent
