---
- name: Install ubuntu-pro
  ansible.builtin.import_tasks: install-pro.yaml

- name: Disable unattended upgrades
  ansible.builtin.import_tasks: disable-unattended-upgrades.yaml
  when: selfadmin is not defined

- name: Run install-tanium
  ansible.builtin.import_tasks: install-tanium.yaml
