---
- name: Check NVIDIA hardware and modules for installation status
  block:
    - name: Check for NVIDIA hardware
      shell: lspci | grep -i -q nvidia
      register: nvidia_lspci_check
      ignore_errors: true
      changed_when: false

    - name: Check for NVIDIA kernel modules
      shell: lsmod | grep -q nvidia
      register: nvidia_modules_check
      ignore_errors: true
      changed_when: false
      when: nvidia_lspci_check.rc == 0

- name: Install NVIDIA components
  include_tasks: install-nvidia.yaml
  when: nvidia_lspci_check.rc == 0 and nvidia_modules_check.rc|default(0) != 0

- name: Notify if NVIDIA drivers are already installed
  debug:
    msg: "NVIDIA drivers are already installed. Skipping automatic installation."
  when: nvidia_lspci_check.rc == 0 and nvidia_modules_check.rc|default(0) == 0
  changed_when: false

- name: Notify if NVIDIA hardware is not present
  debug:
    msg: "No NVIDIA hardware detected. Skipping automatic installation."
  when: nvidia_lspci_check.rc != 0
  changed_when: false
