--- 
- name: (MOTD) motd file
  ansible.builtin.copy:
    src: "files/etc/motd"
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'

- name: (MOTD) disable motd-news
  ansible.builtin.copy:
    src: "files/etc/default/motd-news"
    dest: /etc/default/motd-news
    owner: root
    group: root
    mode: '0644'
