---
- name: (APT) Set repository to local KSoC mirror
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/official-package-repositories.list
    regexp: '^deb\s+http:\/\/archive\.ubuntu\.com\/ubuntu'
    replace: 'deb http://ubuntu.cs.utah.edu/ubuntu'
  register: ubuntu_mirror
  notify: update apt cache
  changed_when: ubuntu_mirror is changed

- name: (APT) Set Mint repository to local Xmission mirror
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/official-package-repositories.list
    regexp: '^deb\s+http:\/\/packages\.linuxmint\.com'
    replace: 'deb https://mirrors.xmission.com/linuxmint'
  register: mint_mirror
  notify: update apt cache
  changed_when: mint_mirror is changed

- name: Force handler execution after apt changes (Mint)
  meta: flush_handlers
  when: ubuntu_mirror is changed or mint_mirror is changed
