---
- name: (SSH) sshd_config
  ansible.builtin.copy:
    src: "files/ssh/sshd_config"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: restart sshd

- name: (SSH) uusci.conf
  ansible.builtin.copy:
    src: "files/ssh/uusci.conf"
    dest: /etc/ssh/sshd_config.d/uusci.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart sshd

- name: (SSH) ssh-audit_hardening.conf
  ansible.builtin.copy:
    src: "files/ssh/ssh-audit_hardening.conf"
    dest: /etc/ssh/sshd_config.d/ssh-audit_hardening.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart sshd
