
- name: reload sysctl-swappiness
  ansible.builtin.shell:
    cmd: /usr/sbin/sysctl -p /etc/sysctl.d/50-swappiness.conf

- name: reload sysctl-ipv6
  ansible.builtin.shell:
    cmd: /usr/sbin/sysctl -p /etc/sysctl.d/50-ipv6.conf