---
- name: Remove buildtemp user
  ansible.builtin.user:
    name: buildtemp
    state: absent
    remove: true

- name: Set timezone
  ansible.builtin.timezone:
    name: America/Denver

- name: Generate /etc/hosts
  template:
    src=templates/hosts.j2
    dest=/etc/hosts

- name: Configure /etc/passwd for generic users (no access)
  ansible.builtin.lineinfile:
    path: /etc/passwd
    line: '+::0:0:::/usr/sbin/nologin'
    state: present
    regexp: '^\+:'
    insertafter: 'EOF'

- name: Configure /etc/passwd for it-users
  ansible.builtin.lineinfile:
    path: /etc/passwd
    line: '+@it-users::0:0:::'
    state: present
    regexp: '@it-users'
    insertbefore: '^\+'

- name: Configure /etc/group
  ansible.builtin.lineinfile:
    path: /etc/group
    line: "+:::"
    state: present
    insertafter: EOF

- name: Configure swappiness
  when: inventory_hostname not in groups["StarfishHosts"] and inventory_hostname not in groups["Desktops"]
  ansible.builtin.copy:
    src: "files/sysctl/50-swappiness.conf"
    dest: /etc/sysctl.d/50-swappiness.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload sysctl-swappiness

- name: Configure ipv6
  ansible.builtin.copy:
    src: "files/sysctl/50-ipv6.conf"
    dest: /etc/sysctl.d/50-ipv6.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload sysctl-ipv6
  
  