---
#
# This playbook will make sure the packges provided through apt are up 
# to date (but will not reboot boxes; that is a different playbook)
#
- hosts: '{{ ansible_limit | default(omit) }}'
  gather_facts: false
  tasks: 
  - name: Decrypt secret
    set_fact:
      decrypted_secret: "{{ test-secrets }}"
  - name: Read the secret
    debug: msg="{{ decrypted_secret }}"