---
#
# This playbook will make sure the packges provided through apt are up 
# to date (but will not reboot boxes; that is a different playbook)
#
- hosts: '{{ ansible_limit | default(omit) }}'
  gather_facts: false
  tasks: 
  - name: Vault-thing
    debug: msg="{{ test-secrets }}"